; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericAT32F403ACCT7]
platform = arterytekat32
board = genericAT32F403ACCT7
framework = at32firmlib
build_flags = 
    -Iinclude
    -mcpu=cortex-m4
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard

extra_scripts = pre:extra_fpu.py

build_type = debug    ; or release (default: debug)
middlewares = freertos, usbd_drivers
board_build.freertos_heap = heap_2.c
upload_protocol = dfu          ; USB DFU bootloader
; upload_protocol = stlink       ; ST-Link
debug_tool = stlink